Document: kiwi
Title: Debian kiwi Manual
Author: <insert document author here>
Abstract: This manual describes what kiwi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kiwi/kiwi.sgml.gz

Format: postscript
Files: /usr/share/doc/kiwi/kiwi.ps.gz

Format: text
Files: /usr/share/doc/kiwi/kiwi.text.gz

Format: HTML
Index: /usr/share/doc/kiwi/html/index.html
Files: /usr/share/doc/kiwi/html/*.html
